### ISSUE TITLE
Installation Failiure

### ISSUE THREAD

**Issue by jamieluckett** [ChainsDD/Superuser#1]
Hey.
I tried to install Superuser 2.3 onto my Samsung Galaxy Portal/Spica/Lite with Android 2.1. When flashing via recovery I got the following error message.
Installing Files
Deleting Files
Copying Files
E: Error in fixsuperm
(Status 65280)
E: Failure at line 8:
run_program PACKAGE:fixsuperm
Installation aborted.

Any idea why?

**Comment by ChainsDD** [comment]
Looks like your phone doesn't like fixsuperm, did you have an older version of Superuser installed, or was this the first? You can try taking fixsuperm out of the update.zip and update-script. It'll install that way, but if you had an older version of Superuser you may need to run fix_permissions

**Comment by jamieluckett** [comment]
This was the first version of YOUR superuser I've installed. I did have the original one that comes with most roms.
How to I get rid of fixsuperm from my update zip? Is it just a matter of finding it and deleting it?

**Comment by ChainsDD** [comment]
http://bit.ly/cC0Irc Got it right here for you. Give that a shot.

**Comment by jamieluckett** [comment]
Ok. That flashed successfully but opening it gives me a FC. Apps that need root claim that I'm not rooted.
