### ISSUE TITLE
Force Close at variable stages

### ISSUE THREAD

**Issue by jostrander** [ChainsDD/Superuser#36]
Force closes all the time, when on the accept/deny dialog, and in the app, has something to do with the sqlite database from what I could gather.

Logcat: with FC's

http://pastebin.com/dz4LJ5P0

**Comment by lilyanatia** [comment]
looks like the same issue i've been having... the owner of the database files keeps getting changed. i keep changing it back and it works for a while, but it eventually breaks again. i haven't had time to look at how to actually fix the problem in the app.

_Sent via Hubroid_

**Comment by ChainsDD** [comment]
Your database is having it's owner changed? Can you record that some how? Maybe keep an eye out for it, and get me the output of "ls -l /data/data/com.noshufou.android.su/databases" when it happens? As far as I've seen so far, the only issue with the database is the WAL logging which locks the database when it's open in the su binary.

**Comment by lilyanatia** [comment]
here you go:
 total 140
-rw-rw----    1 10124    10124         7168 Oct 14 21:46 permissions.sqlite
-rw-rw----    1 0        0            32768 Oct 14 21:47 permissions.sqlite-shm
-rw-rw----    1 0        0                0 Oct 14 21:46 permissions.sqlite-wal
-rw-rw----    1 10124    10124        11264 Oct 11 20:28 su.db
-rw-rw-rw-    1 10124    10124        32768 Oct 14 21:47 su.db-shm
-rw-rw-rw-    1 10124    10124        48240 Oct 14 21:47 su.db-wal
-rw-rw----    1 10124    10124        15360 Oct  5 22:22 webview.db
-rw-rw----    1 10124    10124        32768 Oct 11 20:28 webview.db-shm
-rw-rw----    1 10124    10124            0 Oct  5 22:22 webview.db-wal
-rw-rw----    1 10124    10124         6144 Oct  5 22:22 webviewCache.db
-rw-rw----    1 10124    10124        32768 Oct 11 20:28 webviewCache.db-shm
-rw-rw----    1 10124    10124            0 Oct  5 22:22 webviewCache.db-wal

changing the owner and group of permissions.sqlite-shm and permissions.sqlite-wal to match the other files makes it work without force closing for a while.

**Comment by jostrander** [comment]
After latest update, still getting the owner changed...i chowned the two files, and it worked for 1 "remembered" allow, then the permissions were claimed by root. Ex:

# ls -l

ls -l
-rw-rw---- root     root        32768 2011-10-20 19:40 permissions.sqlite-shm
-rw-rw---- root     root            0 2011-10-20 19:40 permissions.sqlite-wal
-rw-rw---- app_119  app_119     32768 2011-10-20 19:40 su.db-shm
-rw-rw---- app_119  app_119     27280 2011-10-20 19:40 su.db-wal
-rw-rw---- app_119  app_119      8192 2011-10-20 19:40 permissions.sqlite
-rw-rw---- app_119  app_119      7168 2011-10-20 19:37 su.db
-rw-rw---- app_119  app_119      6144 2011-10-20 19:37 webviewCache.db
-rw-rw---- app_119  app_119     15360 2011-10-20 19:37 webview.db

**Comment by ChainsDD** [comment]
I think we've found a fix for this in the su binary. I will be releasing an updated version to be downloaded through the binary updater or flashable zip later today

**Comment by ChainsDD** [comment]
Closing this issue as I haven't heard of any issues with the current builds
