### ISSUE TITLE
App name format issue in Traditional Chinese resource

### ISSUE THREAD

**Issue by boypt** [ChainsDD/Superuser#41]
When set to Traditional Chinese, the notification text when an app asked for root permission, shows "％s 已被授予超級用戶權限", the "％s" is not formatted into the actual app name because the unicode character "％" won't be recognized to be a string format.

I reviewed the resource file : res/values-zh-rTW/strings.xml , there are 3 in"％" existed, i suggest this patch:

``` diff
--- strings.orig.xml    2012-01-08 17:17:03.355563806 +0800
+++ strings.xml 2012-01-08 17:19:31.021993707 +0800
@@ -38,7 +38,7 @@
   <string name="toggled">已切換</string>
   <string name="empty_apps">在清單中沒有應用程式</string>
   <string name="empty_logs">沒有記錄資訊</string>
-  <string name="log_count">顯示％d個項目</string>
+  <string name="log_count">顯示%d個項目</string>
   <string name="detail_package">包封</string>
   <string name="detail_app_uid">應用程序的UID</string>
   <string name="detail_request">請求的 UID</string>
@@ -151,8 +151,8 @@
   <string name="updater_bad_install_location">su 二進位目前安裝於 /sbin 中。此更新程式無法對其進行更新。請尋找適用於您裝置的新的 ROM。</string>
   <string name="updater_bad_install_location_explained">This updater is incapable of updating your su binary since it is installed in /sbin. This is not an error in the updater, it is an error on the behalf of your ROM or kernel developer. You can continue to use Superuser with your outdated binary.</string>
   <string name="updater_failed_remount">This updater cannot update the su binary on phones that have some kind of write protection on the system partition like S-ON. You can continue to use Superuser with your outdated binary, or update su with ROM Manager.</string>
-  <string name="notification_text_allow">％s 已被授予超級用戶權限</string>
-  <string name="notification_text_deny">％s 已被拒絕超級用戶權限</string>
+  <string name="notification_text_allow">%s 已被授予超級用戶權限</string>
+  <string name="notification_text_deny">%s 已被拒絕超級用戶權限</string>
   <string name="notif_outdated_ticker">你的su二進制文件已過時</string>
   <string name="notif_outdated_title">su二進制文件過時</string>
   <string name="notif_outdated_text">點擊以更新su二進制文件</string>


```

**Comment by dove0rz** [comment]
％ is 2 bytes, change to one byte % plz.

**Comment by x43x61x69** [comment]
I made a batter translation which also fixed the above problem:

<pre>
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;resources&gt;
    &lt;string name=&quot;app_name&quot;&gt;超級使用者&lt;/string&gt;
    &lt;string name=&quot;app_name_request&quot;&gt;超級使用者要求&lt;/string&gt;
    &lt;string name=&quot;description_home&quot;&gt;首頁&lt;/string&gt;
    &lt;string name=&quot;description_log&quot;&gt;記錄&lt;/string&gt;
    &lt;string name=&quot;description_preferences&quot;&gt;偏好設定&lt;/string&gt;
    &lt;string name=&quot;description_extras&quot;&gt;附加&lt;/string&gt;
    &lt;string name=&quot;menu_extras&quot;&gt;附加&lt;/string&gt;
    &lt;string name=&quot;menu_preferences&quot;&gt;偏好設定&lt;/string&gt;
    &lt;string name=&quot;menu_clear&quot;&gt;清除&lt;/string&gt;
    &lt;string name=&quot;menu_clear_log&quot;&gt;清除記錄&lt;/string&gt;
    &lt;string name=&quot;permgrouplab_superuser&quot;&gt;超級使用者權限&lt;/string&gt;
    &lt;string name=&quot;permgroupdesc_superuser&quot;&gt;與超級使用者有關的權限&lt;/string&gt;
    &lt;string name=&quot;permlab_respond&quot;&gt;回應超級使用者的請求&lt;/string&gt;
    &lt;string name=&quot;permdesc_respond&quot;&gt;允許應用程式回應超級使用者的存取請求&lt;/string&gt;
    &lt;string name=&quot;permlab_provider_read&quot;&gt;讀取超級使用者資料&lt;/string&gt;
    &lt;string name=&quot;permdesc_provider_read&quot;&gt;允許應用程式從超級使用者的內容提供者讀取資料&lt;/string&gt;
    &lt;string name=&quot;permlab_provider_write&quot;&gt;寫入超級使用者資料&lt;/string&gt;
    &lt;string name=&quot;permdesc_provider_write&quot;&gt;允許應用程式向超級使用者的內容提供者寫入資料&lt;/string&gt;
    &lt;string name=&quot;recent_activity&quot;&gt;最近的活動&lt;/string&gt;
    &lt;string name=&quot;yes&quot;&gt;是&lt;/string&gt;
    &lt;string name=&quot;no&quot;&gt;否&lt;/string&gt;
    &lt;string name=&quot;ok&quot;&gt;確定&lt;/string&gt;
    &lt;string name=&quot;loading&quot;&gt;載入中...&lt;/string&gt;
    &lt;string name=&quot;allow&quot;&gt;允許&lt;/string&gt;
    &lt;string name=&quot;cancel&quot;&gt;取消&lt;/string&gt;
    &lt;string name=&quot;deny&quot;&gt;拒絕&lt;/string&gt;
    &lt;string name=&quot;set&quot;&gt;設定&lt;/string&gt;
    &lt;string name=&quot;remember&quot;&gt;記住&lt;/string&gt;
    &lt;string name=&quot;remember_disabled&quot;&gt;直到 su 更新前，記住停用&lt;/string&gt;
    &lt;string name=&quot;request&quot;&gt;%1$s 作為 %2$s (uid: %3$d)&lt;/string&gt;
    &lt;string name=&quot;unknown&quot;&gt;未知的名稱&lt;/string&gt;
    &lt;string name=&quot;allowed&quot;&gt;已允許&lt;/string&gt;
    &lt;string name=&quot;denied&quot;&gt;已拒絕&lt;/string&gt;
    &lt;string name=&quot;created&quot;&gt;已建立&lt;/string&gt;
    &lt;string name=&quot;toggled&quot;&gt;已切換&lt;/string&gt;
    &lt;string name=&quot;empty_apps&quot;&gt;在清單中沒有應用程式&lt;/string&gt;
    &lt;string name=&quot;empty_logs&quot;&gt;沒有記錄資訊&lt;/string&gt;
    &lt;string name=&quot;log_count&quot;&gt;顯示 %d 個項目&lt;/string&gt;
    &lt;string name=&quot;detail_package&quot;&gt;包封&lt;/string&gt;
    &lt;string name=&quot;detail_app_uid&quot;&gt;應用程序的 UID&lt;/string&gt;
    &lt;string name=&quot;detail_request&quot;&gt;請求的 UID&lt;/string&gt;
    &lt;string name=&quot;detail_command&quot;&gt;命令&lt;/string&gt;
    &lt;string name=&quot;detail_status&quot;&gt;狀態&lt;/string&gt;
    &lt;string name=&quot;request_app_name&quot;&gt;應用程式&lt;/string&gt;
    &lt;string name=&quot;pref_title&quot;&gt;偏好設定&lt;/string&gt;
    &lt;string name=&quot;pref_category_security&quot;&gt;安全性&lt;/string&gt;
    &lt;string name=&quot;pref_pin_title&quot;&gt;使用 PIN&lt;/string&gt;
    &lt;string name=&quot;pref_change_pin_title&quot;&gt;更改 PIN&lt;/string&gt;
    &lt;string name=&quot;pref_timeout_title&quot;&gt;訪問超時&lt;/string&gt;
    &lt;string name=&quot;pref_automatic_action_title&quot;&gt;自動回應&lt;/string&gt;
    &lt;string name=&quot;pref_automatic_action_summary&quot;&gt;設置超級用戶處理新請求的方式&lt;/string&gt;
    &lt;string name=&quot;pref_ghost_mode_title&quot;&gt;幽靈模式&lt;/string&gt;
    &lt;string name=&quot;pref_ghost_mode_summary_off&quot;&gt;幽靈模式停用&lt;/string&gt;
    &lt;string name=&quot;pref_secret_code_title&quot;&gt;密碼&lt;/string&gt;
    &lt;string name=&quot;pref_secret_code_summary&quot;&gt;密碼是 *#*#%1$s#*#*&lt;/string&gt;
    &lt;string name=&quot;pref_category_applist_title&quot;&gt;應用程式清單&lt;/string&gt;
    &lt;string name=&quot;pref_show_status_icons_title&quot;&gt;顯示狀態圖標&lt;/string&gt;
    &lt;string name=&quot;pref_show_status_icons_summary_on&quot;&gt;顯示每個應用程式狀態的圖標&lt;/string&gt;
    &lt;string name=&quot;pref_show_status_icons_summary_off&quot;&gt;不顯示每個應用程式狀態的圖標&lt;/string&gt;
    &lt;string name=&quot;pref_status_icon_type_title&quot;&gt;狀態圖標類型&lt;/string&gt;
    &lt;string name=&quot;pref_status_icon_type_summary&quot;&gt;狀態圖示以顯示的樣式&lt;/string&gt;
    &lt;string name=&quot;pref_applist_show_log_data_title&quot;&gt;顯示記錄資料&lt;/string&gt;
    &lt;string name=&quot;pref_applist_show_log_data_summary_on&quot;&gt;在應用程式清單中顯示記錄資料&lt;/string&gt;
    &lt;string name=&quot;pref_applist_show_log_data_summary_off&quot;&gt;不要在應用程式清單中顯示記錄資料&lt;/string&gt;
    &lt;string name=&quot;pref_category_log_title&quot;&gt;記錄&lt;/string&gt;
    &lt;string name=&quot;pref_enable_logging_title&quot;&gt;啟用記錄&lt;/string&gt;
    &lt;string name=&quot;pref_enable_logging_summary_on&quot;&gt;建立或存取權限將被記錄&lt;/string&gt;
    &lt;string name=&quot;pref_enable_logging_summary_off&quot;&gt;建立或存取權限將不被記錄&lt;/string&gt;
    &lt;string name=&quot;pref_delete_old_logs_title&quot;&gt;刪除舊記錄項目&lt;/string&gt;
    &lt;string name=&quot;pref_delete_old_logs_summary_on&quot;&gt;當到達限制時，刪除舊的記錄項目&lt;/string&gt;
    &lt;string name=&quot;pref_delete_old_logs_summary_off&quot;&gt;當到達限制時，不刪除舊的記錄項目&lt;/string&gt;
    &lt;string name=&quot;pref_log_entry_limit_title&quot;&gt;記錄項目限制&lt;/string&gt;
    &lt;string name=&quot;pref_log_entry_limit_summary&quot;&gt;%1$d 個記錄項目&lt;/string&gt;
    &lt;string name=&quot;pref_log_entries_to_save&quot;&gt;設定要儲存的記錄項目數量&lt;/string&gt;
    &lt;string name=&quot;pref_24_hour_title&quot;&gt;使用 24 小時制&lt;/string&gt;
    &lt;string name=&quot;pref_24_hour_summary_on&quot;&gt;記錄的時間將以 24 小時制顯示&lt;/string&gt;
    &lt;string name=&quot;pref_24_hour_summary_off&quot;&gt;記錄的時間將以 12 小時制顯示&lt;/string&gt;
    &lt;string name=&quot;pref_show_seconds_title&quot;&gt;顯示秒數&lt;/string&gt;
    &lt;string name=&quot;pref_show_seconds_summary_on&quot;&gt;記錄的時間將包含秒數&lt;/string&gt;
    &lt;string name=&quot;pref_show_seconds_summary_off&quot;&gt;記錄的時間將不包含秒數&lt;/string&gt;
    &lt;string name=&quot;pref_date_format_title&quot;&gt;選取日期格式&lt;/string&gt;
    &lt;string name=&quot;pref_date_format_summary&quot;&gt;在所有記錄中用於顯示日期的格式&lt;/string&gt;
    &lt;string name=&quot;pref_clear_log_title&quot;&gt;清除記錄&lt;/string&gt;
    &lt;string name=&quot;pref_clearing_log_title&quot;&gt;正在清除記錄&lt;/string&gt;
    &lt;string name=&quot;pref_clearing_log_summary&quot;&gt;請稍候&lt;/string&gt;
    &lt;string name=&quot;pref_category_notification_title&quot;&gt;通知&lt;/string&gt;
    &lt;string name=&quot;pref_notifications_title&quot;&gt;通知&lt;/string&gt;
    &lt;string name=&quot;pref_notifications_summary_on&quot;&gt;當應用程式取得 su 權限時顯示通知&lt;/string&gt;
    &lt;string name=&quot;pref_notifications_summary_off&quot;&gt;當應用程式取得 su 權限時不顯示通知&lt;/string&gt;
    &lt;string name=&quot;pref_notifications_type_title&quot;&gt;通知類型&lt;/string&gt;
    &lt;string name=&quot;pref_notifications_type_summary&quot;&gt;當應用程式取得 su 權限時所顯示的通知類型&lt;/string&gt;
    &lt;string name=&quot;pref_toast_location_title&quot;&gt;吐司通知位置&lt;/string&gt;
    &lt;string name=&quot;pref_toast_location_summary&quot;&gt;通知訊息在螢幕上顯示的位置&lt;/string&gt;
    &lt;string name=&quot;pref_category_nfc_title&quot;&gt;NFC&lt;/string&gt;
    &lt;string name=&quot;pref_use_allow_tag_title&quot;&gt;使用 NFC 標記方可允許&lt;/string&gt;
    &lt;string name=&quot;pref_use_allow_tag_summary_on&quot;&gt;輸入 PIN 或掃描標記方可允許&lt;/string&gt;
    &lt;string name=&quot;pref_use_allow_tag_summary_off&quot;&gt;只有輸入 PIN 方可允許&lt;/string&gt;
    &lt;string name=&quot;pref_write_allow_tag_title&quot;&gt;寫入新允許標記&lt;/string&gt;
    &lt;string name=&quot;pref_write_allow_tag_summary&quot;&gt;寫入用於允許的新標記&lt;/string&gt;
    &lt;string name=&quot;pref_category_backup_restore_title&quot;&gt;備份/還原&lt;/string&gt;
    &lt;string name=&quot;pref_backup_title&quot;&gt;備份應用程式 / 偏好設定&lt;/string&gt;
    &lt;string name=&quot;backup_complete&quot;&gt;備份至記憶卡&lt;/string&gt;
    &lt;string name=&quot;pref_restore_title&quot;&gt;還原應用程式 / 偏好設定&lt;/string&gt;
    &lt;string name=&quot;restore_complete_prefs_only&quot;&gt;偏好設定已還原&lt;/string&gt;
    &lt;string name=&quot;pref_category_info_title&quot;&gt;一般&lt;/string&gt;
    &lt;string name=&quot;pref_version_title&quot;&gt;超級用戶 v%1$s (%2$d)&lt;/string&gt;
    &lt;string name=&quot;pref_version_summary&quot;&gt;資料庫版本 %s&lt;/string&gt;
    &lt;string name=&quot;pref_bin_version_title_loading&quot;&gt;正在載入二進制文件版本...&lt;/string&gt;
    &lt;string name=&quot;pref_bin_version_title&quot;&gt;su 二進制文件 v%s&lt;/string&gt;
    &lt;string name=&quot;pref_bin_version_summary&quot;&gt;點擊以檢查新版本&lt;/string&gt;
    &lt;string name=&quot;pref_outdated_notification_title&quot;&gt;二進制文件更新通知&lt;/string&gt;
    &lt;string name=&quot;pref_outdated_notification_summary_on&quot;&gt;當有新版本的二進制文件時顯示通知&lt;/string&gt;
    &lt;string name=&quot;pref_outdated_notification_summary_off&quot;&gt;當有新版本的二進制文件時不顯示通知&lt;/string&gt;
    &lt;string name=&quot;pref_advanced_prompt_title&quot;&gt;使用進階存取請求&lt;/string&gt;
    &lt;string name=&quot;pref_advanced_prompt_summary_on&quot;&gt;於進階存取請求時不顯示警告&lt;/string&gt;
    &lt;string name=&quot;pref_advanced_prompt_summary_off&quot;&gt;於進階存取請求時顯示警告&lt;/string&gt;
    &lt;string name=&quot;pref_changelog_title&quot;&gt;變更日誌&lt;/string&gt;
    &lt;string name=&quot;pref_changelog_summary&quot;&gt;顯示變更日誌&lt;/string&gt;
    &lt;string name=&quot;pref_get_elite_title&quot;&gt;菁英版！&lt;/string&gt;
    &lt;string name=&quot;pref_get_elite_summary&quot;&gt;購買菁英版以解鎖所有選項&lt;/string&gt;
    &lt;string name=&quot;updater_title&quot;&gt;二進制文件更新&lt;/string&gt;
    &lt;string name=&quot;updater_new_su_found&quot;&gt;發現新版本的二進制文件，要更新嗎？&lt;/string&gt;
    &lt;string name=&quot;updater_current_installed&quot;&gt;目前已安裝最新版本，不需要更新。&lt;/string&gt;
    &lt;string name=&quot;updater_update&quot;&gt;更新&lt;/string&gt;
    &lt;string name=&quot;updater_cool&quot;&gt;不錯喔！再更新一次。&lt;/string&gt;
    &lt;string name=&quot;updater_working&quot;&gt;執行中...&lt;/string&gt;
    &lt;string name=&quot;updater_ok&quot;&gt;完成！&lt;/string&gt;
    &lt;string name=&quot;updater_fail&quot;&gt;失敗！&lt;/string&gt;
    &lt;string name=&quot;updater_update_failed&quot;&gt;更新失敗。再試一次？&lt;/string&gt;
    &lt;string name=&quot;updater_try_again&quot;&gt;再試一次&lt;/string&gt;
    &lt;string name=&quot;updater_su_updated&quot;&gt;su 二進制更新成功&lt;/string&gt;
    &lt;string name=&quot;updater_step_latest_version&quot;&gt;&quot;最新版本：&quot;&lt;/string&gt;
    &lt;string name=&quot;updater_step_check_installed_version&quot;&gt;&quot;檢查以安裝的版本= &quot;&lt;/string&gt;
    &lt;string name=&quot;updater_step_fix_db&quot;&gt;&quot;修復資料庫 ...  &quot;&lt;/string&gt;
    &lt;string name=&quot;updater_step_download_busybox&quot;&gt;&quot;下載自訂 busybox... &quot;&lt;/string&gt;
    &lt;string name=&quot;updater_step_check_md5sum&quot;&gt;&quot;檢查 md5sum... &quot;&lt;/string&gt;
    &lt;string name=&quot;updater_step_check_installed_path&quot;&gt;&quot;正在檢查目前安裝路徑... &quot;&lt;/string&gt;
    &lt;string name=&quot;updater_step_download_su&quot;&gt;&quot;正在下載新的二進制文件... &quot;&lt;/string&gt;
    &lt;string name=&quot;updater_step_get_root&quot;&gt;&quot;獲得 root 權限 ...  &quot;&lt;/string&gt;
    &lt;string name=&quot;updater_step_remount_rw&quot;&gt;&quot;重新掛載 /system 為可讀寫...  &quot;&lt;/string&gt;
    &lt;string name=&quot;updater_step_cp&quot;&gt;&quot;複製 su 到/system ...  &quot;&lt;/string&gt;
    &lt;string name=&quot;updater_step_chmod&quot;&gt;&quot;變更 su 檔案權限為 06755... &quot;&lt;/string&gt;
    &lt;string name=&quot;updater_step_mv&quot;&gt;&quot;正在將 su 移至其最終位置... &quot;&lt;/string&gt;
    &lt;string name=&quot;updater_step_remount_ro&quot;&gt;&quot;重新掛載 /system 為唯讀... &quot;&lt;/string&gt;
    &lt;string name=&quot;updater_step_clean_up&quot;&gt;&quot;清理中...  &quot;&lt;/string&gt;
    &lt;string name=&quot;updater_remount_ro_failed&quot;&gt;重新將系統掛載為唯讀失敗，請重新開機以便完成更新&lt;/string&gt;
    &lt;string name=&quot;updater_find_su_failed&quot;&gt;無法找到目前已安裝的 su 二進制文件，更新無法繼續&lt;/string&gt;
    &lt;string name=&quot;updater_bad_install_location&quot;&gt;su 二進位目前安裝於 /sbin 中，此更新程式無法對其進行更新。請尋找適用於您裝置的新的 ROM。&lt;/string&gt;
    &lt;string name=&quot;updater_bad_install_location_explained&quot;&gt;su 二進位目前安裝於 /sbin 中，此更新程式無法對其進行更新。這並非更新程式錯誤，此錯誤是由您所使用的 ROM 或 kernel 開發者所造成。您可以繼續使用使用舊版的二進制文件。&lt;/string&gt;
    &lt;string name=&quot;updater_failed_remount&quot;&gt;此更新程式無法更新受磁區寫入保護（如 S-ON）的 su 二進制文件。您可以繼續使用使用舊版的二進制文件，或使用 ROM Manager 來更新 su。&lt;/string&gt;
    &lt;string name=&quot;notification_text_allow&quot;&gt;%s 已被授予超級用戶權限&lt;/string&gt;
    &lt;string name=&quot;notification_text_deny&quot;&gt;%s 已被拒絕超級用戶權限&lt;/string&gt;
    &lt;string name=&quot;notif_outdated_ticker&quot;&gt;有新版本的 su 二進制文件可供更新&lt;/string&gt;
    &lt;string name=&quot;notif_outdated_title&quot;&gt;su 二進制文件過時&lt;/string&gt;
    &lt;string name=&quot;notif_outdated_text&quot;&gt;點擊以更新 su 二進制文件&lt;/string&gt;
    &lt;string name=&quot;pin_enter_pin&quot;&gt;輸入 PIN&lt;/string&gt;
    &lt;string name=&quot;pin_new_pin&quot;&gt;輸入新的 PIN&lt;/string&gt;
    &lt;string name=&quot;pin_confirm_pin&quot;&gt;確認 PIN&lt;/string&gt;
    &lt;string name=&quot;pin_mismatch&quot;&gt;&quot;兩次輸入的 PIN 不符，請再試一次&quot;&lt;/string&gt;
    &lt;string name=&quot;pin_enter_secret_code&quot;&gt;請輸入密碼&lt;/string&gt;
    &lt;string name=&quot;malicious_apps_title&quot;&gt;警告&lt;/string&gt;
    &lt;string name=&quot;malicious_apps_uninstall&quot;&gt;解除安裝&lt;/string&gt;
    &lt;string name=&quot;malicious_apps_ignore&quot;&gt;忽略&lt;/string&gt;
    &lt;string name=&quot;malicious_app_notification_ticker&quot;&gt;偵測到潛在的惡意程式&lt;/string&gt;
    &lt;string name=&quot;malicious_app_notification_text&quot;&gt;%s 可能為潛在的惡意程式。點擊以解除安裝它。&lt;/string&gt;
    &lt;string name=&quot;malicious_app_uid&quot;&gt;與超級使用者共用 UID&lt;/string&gt;
    &lt;string name=&quot;malicious_app_respond&quot;&gt;請求回應權限&lt;/string&gt;
    &lt;string name=&quot;malicious_app_write&quot;&gt;請求可寫入權限提供者的權限&lt;/string&gt;
    &lt;string name=&quot;changelog_full_title&quot;&gt;變更&lt;/string&gt;
    &lt;string name=&quot;changelog_title&quot;&gt;更新內容&lt;/string&gt;
&lt;/resources&gt;
</pre>

**Comment by boypt** [comment]
The issue is fixed on commit #cba93cb ,  close issue.
