### ISSUE TITLE
Superuser not working on 4.0.4 Galaxy nexus

### ISSUE THREAD

**Issue by rhcp011235** [ChainsDD/Superuser#43]
This was found during a logcat:

I/System  ( 1010): libcore.io.ErrnoException: kill failed: ESRCH (No such process)

**Comment by rhcp011235** [comment]
Full logcat:
E[/su      ( 1950): sudb - Opening database
E/su      ( 1950): sudb - Database opened
E/su      ( 1950): sudb - Database closed
E/ActivityManager(  178): Activity Manager Crash
E/ActivityManager(  178): java.lang.IllegalArgumentException: Unknown URI type: 7
E/ActivityManager(  178):  at android.net.Uri$1.createFromParcel(Uri.java:1734)
E/ActivityManager(  178):  at android.net.Uri$1.createFromParcel(Uri.java:1723)
E/ActivityManager(  178):  at android.content.Intent.readFromParcel(Intent.java:6131)
E/ActivityManager(  178):  at android.content.Intent.<init>(Intent.java:6126)
E/ActivityManager(  178):  at android.content.Intent.readFromParcel(Intent.java:6153)
E/ActivityManager(  178):  at android.content.Intent.<init>(Intent.java:6126)
E/ActivityManager(  178):  at android.content.Intent$1.createFromParcel(Intent.java:6117)
E/ActivityManager(  178):  at android.content.Intent$1.createFromParcel(Intent.java:6115)
E/ActivityManager(  178):  at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:298)
E/ActivityManager(  178):  at .android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:1545)
E/ActivityManager(  178):  at android.os.Binder.execTransact(Binder.java:338)
E/ActivityManager(  178):  at dalvik.system.NativeStart.run(Native Method)
E/su      ( 1950): select failed with 2: No such file or directory
W/su      ( 1950): request rejected (10071->0 /system/bin/sh)

**Comment by rhcp011235** [comment]
Btw, if you need to contact me on gtalk. rhcp011235@gmail.com. I am EST and on most of the time. if you need help to debug.

**Comment by ChainsDD** [comment]
What version of the su binary are you using? Open a terminal, or adb shell, and run "su -v"

**Comment by rhcp011235** [comment]
root@android:/ # su -v
3.0.3

**Comment by ChainsDD** [comment]
Try updating your binary to version 3.0.3.2. This looks a lot like a known issue on ICS 4.0.3 that was fixed for in 3.0.3.2.

**Comment by rhcp011235** [comment]
well.

A) http://downloads.androidsu.com/superuser/su-bin-3.0.3.2-efghi-signed.zip
if i try to flash this in CWM it fails. assert issue.

B) I pushed the su bin from it by hand. it works. 

Thanks!

**Comment by rhcp011235** [comment]
Btw, thanks for the super quick reply. I guess it was pure idiot of me. :)

**Comment by ChainsDD** [comment]
No problem, happens to the best of us :-)
