### ISSUE TITLE
Superuser don't keep track of permissions

### ISSUE THREAD

**Issue by cova-fe** [ChainsDD/Superuser#7]
Hi, 
I'm experiencing an issue with superuser: every time it asks for some permissions I grant it but the permission is not stored and every time I have to re-enter it.
I tried to wipe dalvik-cache and reinstall the app with no changes.

Can someone give me some hints?

Many thanks.

log shows this:
V/WindowManager( 2250): Dsptch 1 x86.0 y627.0 > Window{482a0e20 com.noshufou.android.su/com.noshufou.android.su.SuRequest paused=false}
E/Database( 2984): Error inserting package=com.noshufou.android.su uid=10079 exec_uid=0 allow=1 name=Superuser exec_cmd=/system/bin/sh
E/Database( 2984): android.database.sqlite.SQLiteConstraintException: error code 19: constraint failed
E/Database( 2984):      at android.database.sqlite.SQLiteStatement.native_execute(Native Method)
E/Database( 2984):      at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:66)
E/Database( 2984):      at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1522)
E/Database( 2984):      at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1382)
E/Database( 2984):      at com.noshufou.android.su.DBHelper.insert(DBHelper.java:87)
E/Database( 2984):      at com.noshufou.android.su.SuRequest.onClick(SuRequest.java:109)
E/Database( 2984):      at android.view.View.performClick(View.java:2417)
E/Database( 2984):      at android.view.View.onTouchEvent(View.java:4232)
E/Database( 2984):      at android.widget.TextView.onTouchEvent(TextView.java:6583)
E/Database( 2984):      at android.view.View.dispatchTouchEvent(View.java:3762)
E/Database( 2984):      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:884)
E/Database( 2984):      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:884)
E/Database( 2984):      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:884)
E/Database( 2984):      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:884)
E/Database( 2984):      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1713)
E/Database( 2984):      at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1131)
E/Database( 2984):      at android.app.Activity.dispatchTouchEvent(Activity.java:2070)
E/Database( 2984):      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1697)
E/Database( 2984):      at android.view.ViewRoot.handleMessage(ViewRoot.java:1691)
E/Database( 2984):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/Database( 2984):      at android.os.Looper.loop(Looper.java:123)
E/Database( 2984):      at android.app.ActivityThread.main(ActivityThread.java:4363)
E/Database( 2984):      at java.lang.reflect.Method.invokeNative(Native Method)
E/Database( 2984):      at java.lang.reflect.Method.invoke(Method.java:521)
E/Database( 2984):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862)
E/Database( 2984):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
E/Database( 2984):      at dalvik.system.NativeStart.main(Native Method)
D/SuRequest( 2984): Sending result: ALLOW for UID: 10079
D/su      ( 3012): 10079 com.noshufou.android.su executing 0 /system/bin/sh

**Comment by ChainsDD** [comment]
I believe I've fixed this in 2.3.6

**Comment by cova-fe** [comment]
I've dug a bit more into this: If I got it right in my case this behaviour is due to the mimocan's etx4 kernel. Basically this kernel places his own su (an old version) in /sbin/su at each reboot. After this, your superuser app can't find the right version and falls into this issue. Now I'm trying to look into initramfs of mimoncan's kernel to confirm this, but for some reason (endianness, maybe) I'm still trying to get the gzipped segment out of kernel, but I'm pretty sure that my issue lies here.

Thanks for your answer!
