### ISSUE TITLE
superuser problem w/ root explorer

### ISSUE THREAD

**Issue by terenceleechan** [ChainsDD/Superuser#9]
hi!

i have your latest version 2.3.6.1 installed. problem is it won't work well with root explorer but works well w/ other root apps (root explorer keeps on telling me to restart, problem w/ superuser).  my workaround is to turn wifi/data on, then update superuser binary, then root explorer will work. but whenever i reboot my phone, the same problem occurs again and i have to reupdate binary everytime. how to fix this? by the way i'm running froyo cyanogenmod 6 ported to the samsung spica.  thanks a lot, and great job!

terence

**Comment by ChainsDD** [comment]
This is really old more than likely it's an issue with your kernel, or boot.img.
